categories:
  #Core
  - name: "SECT"
    colour: '04;92m'
  - name: "ROBOT"
  - name: "PICKER"
  - name: "SCHEDU"
    colour: '46m'

  #Tasks
  - name: "STAGE"
    colour: '44m'
  - name: "TASK"
    colour: '42m'
  - name: "MODULE"
  - name: "IDEF"
    colour: '45m'

  #Interruptions
  - name: "DRM"
  - name: "DTM"
    colour: '43m'
  - name: "TOC"
  - name: "COMMS"
  - name: "RVIZ"
    colour: '45m'

  #Interactions
  - name: "ACTION"
    colour: '46m'

  #Navigation
  - name: "ROUTE"
    colour: '41m'
  - name: "PLANER"
    colour: '41m'
  - name: "OCCUPY"
    colour: '41m'
  - name: "XROUTE"
    colour: '41m'
  - name: "NAVIG"
    colour: '41m'
  - name: "ROB_PY"
  - name: "VR_ROB"
    colour: '45m'
    reject: true
  - name: "VR_ROC"
    colour: '45m'
    reject: true
  - name: "ROBNAV"

  #Debug
  - name: "OTHER"
  - name: "START"
#    reject: true
  - name: "SETUP"
  - name: "LOG"
  - name: "TEST"
  - name: "DEBUG"

  #Task Specific
  - name: "TPTASK"
  - name: "UVTASK"
  - name: "DCTASK"
    colour: '46m'
  - name: "HEALTH"

ids:
  - name: "COORDINATOR"
    colour: '42m'
  - name: "SECTION"
    colour: '04;92m'

  - name: "PLANNER"
    colour: '41m'
  - name: "MEDIATOR"
    colour: '46m'

  - name: "storage01"
    colour: '31m'
  - name: "thorvald_001"
    colour: '36m'
  - name: "thorvald_002"
    colour: '33m'
  - name: "picker01"
    colour: '34m'
  - name: "picker02"
    colour: '35m'
  - name: "uv1"
    colour: '39m'
  - name: "thorvald_023"
    colour: '36m'
  - name: "thorvald_024"
    colour: '33m'
  - name: "thorvald_025"
    colour: '34m'
#  - name: "STD_v2_246f284a6c94"
#    colour: '35m'
#  - name: "STD_v2_70b8f606c710"
#    colour: '35m'
