modules:
  - name: base
    role: human
  - name: uv_treatment
    role: controller
  - name: data_collection
    role: controller
navigation_properties:
    has_presence: false
visualisation_properties:
    rviz_model: human